- defaults:
    link:
      relink: true
      create: true
      force: true

- clean:
    - '~'
    - '~/.config'

- link:
    ~/.zshrc: zsh/zshrc
    ~/.tmux.conf: tmux/tmux.conf
    ~/.gitconfig: git/gitconfig
    ~/.config/lazygit/config.yml: lazygit/config.yml
    ~/.config/alacritty/alacritty.toml: alacritty/alacritty.toml
    ~/.config/karabiner/karabiner.json: karabiner/karabiner.json
